<?php

session_start();
include("../config.php");

if(!isset($_SESSION['role']) || $_SESSION['role'] != 'faculty')
{
    header("Location: ../login.php");
    exit();
}

$faculty_id = $_SESSION['user_id'];

$faculty_query = "
SELECT
faculty_division,
full_name
FROM users
WHERE id='$faculty_id'
";

$faculty_result = mysqli_query($conn,$faculty_query);
$faculty = mysqli_fetch_assoc($faculty_result);

$faculty_division = $faculty['faculty_division'];
$faculty_name = $faculty['full_name'];

$query = "

SELECT

users.enrollment_no,
users.roll_no,
users.full_name,

student_evaluation.week1_marks,
student_evaluation.week2_marks,
student_evaluation.week3_marks,
student_evaluation.week4_marks,
student_evaluation.weekly_total,
student_evaluation.mentor_evaluation,
student_evaluation.final_evaluation,
student_evaluation.total_marks

FROM users

LEFT JOIN student_evaluation

ON users.id = student_evaluation.student_id

WHERE
users.role='student'
AND users.division='$faculty_division'

ORDER BY CAST(users.roll_no AS UNSIGNED)

";

$result = mysqli_query($conn,$query);

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=Student_Evaluation_".$faculty_division.".xls");
header("Pragma: no-cache");
header("Expires: 0");

?>

<html>

<head>

<meta charset="UTF-8">

<style>

table{

border-collapse:collapse;
width:100%;

}

th,td{

border:1px solid black;
padding:6px;
font-size:12px;
text-align:center;

}

th{

background:#d9d9d9;
font-weight:bold;

}

.title{

font-size:18px;
font-weight:bold;
text-align:center;

}

.subtitle{

font-size:14px;
text-align:center;

}

.left{

text-align:left;

}

</style>

</head>

<body>

<table>

<tr>

<td colspan="11" class="title">

MIT Art, Design and Technology University

</td>

</tr>

<tr>

<td colspan="11" class="subtitle">

Student Internship Evaluation Sheet

</td>

</tr>

<tr>

<td colspan="6" class="left">

<b>Division :</b>
<?php echo $faculty_division; ?>

</td>

<td colspan="5" class="left">

<b>Internship Class Coordinator :</b>
<?php echo $faculty_name; ?>

</td>

</tr>

<tr><td colspan="11"></td></tr>

<tr>

<th>Enrollment No</th>

<th>Roll No</th>

<th>Student Name</th>

<th>Week-1</th>

<th>Week-2</th>

<th>Week-3</th>

<th>Week-4</th>

<th>Week Total (40)</th>

<th>Mentor Evaluation (40)</th>

<th>Final Evaluation (20)</th>

<th>Total Marks (50)</th>

</tr>

<?php

while($row = mysqli_fetch_assoc($result))
{

$week1 = ($row['week1_marks'] != "") ? $row['week1_marks'] : 0;
$week2 = ($row['week2_marks'] != "") ? $row['week2_marks'] : 0;
$week3 = ($row['week3_marks'] != "") ? $row['week3_marks'] : 0;
$week4 = ($row['week4_marks'] != "") ? $row['week4_marks'] : 0;

$weekly = ($row['weekly_total'] != "") ? $row['weekly_total'] : 0;

$mentor = ($row['mentor_evaluation'] != "") ? $row['mentor_evaluation'] : 0;

$final = ($row['final_evaluation'] != "") ? $row['final_evaluation'] : 0;

$total = ($row['total_marks'] != "") ? $row['total_marks'] : 0;

echo "<tr>";

echo "<td>".$row['enrollment_no']."</td>";

echo "<td>".$row['roll_no']."</td>";

echo "<td style='text-align:left;'>".$row['full_name']."</td>";

echo "<td>".$week1."</td>";

echo "<td>".$week2."</td>";

echo "<td>".$week3."</td>";

echo "<td>".$week4."</td>";

echo "<td>".$weekly."</td>";

echo "<td>".$mentor."</td>";

echo "<td>".$final."</td>";

echo "<td>".$total." / 50</td>";

echo "</tr>";

}

?>

</table>

<br><br>

<table>

<tr>

<td style="border:none;font-weight:bold;">
Generated On :
<?php echo date("d-m-Y h:i A"); ?>
</td>

</tr>

<tr>

<td style="border:none;font-weight:bold;">
Generated By :
<?php echo $faculty_name; ?>
</td>

</tr>

<tr>

<td style="border:none;">
MIT Art, Design and Technology University
</td>

</tr>

</table>

</body>

</html>